### PR TITLE
Update FX3 support on fresh libsigrok

### PR DESCRIPTION
**Pull request by zougloub**
Hi @zeldin,

I (imperfectly) rebased your changes on the latest upstream sigrok master and added a "quick fix" which makes the device discoverable after firmware loading (because it is changing speed, it changes USB bus). At this point I just wanted to start a conversation; I can clean-up and try to upstream if you're too busy to do it.

Sorry I haven't tested your original revision, it looks like things are working, except that I noticed that the behavior is inconsistent between <= 64 Msps and   >= 96Msps. For a disconnected logic analyzer, the signal was all ones, and it becomes all zeroes. At first sight I don't think any of this code can be the problem.

### CODE REVIEW

**Comment by zeldin** [comment]
Hi zougloub.  Thank you for your contribution, and sorry about belated reply.

It's difficult for me to review your pull request because it has zeldin:fx3lafw as the base branch, meaning that every commit from mainline is showing up as part of the PR...  Not sure what the best path to proceed would be here.

As for your "quick fix", unfortunately there is no guarantee that only the bus number will change.  The USB2 bus can have a completely different topology from the USB3 one.  For example, on my Talos II, 2-3 (USB3) is the same physical port as 1-4.2 (USB2).  The USB2 side of the connectors is connected via a hub, but the USB3 side goes directly to a root port.

The two highest sample speeds use a different path in the GPIF code, since they are too fast to work with the delay counter.  I don't know why that would affect the readings, but in general the behaviour of sampling unconnected inputs is undefined.

**Comment by ashwinnaircy** [comment]
Take a look at this pull-request (https://github.com/sigrokproject/libsigrok/pull/148). This adds support for using FX3 devices as 100MHz 16 channel logic analyzers using sigrok

**Comment by zougloub** [comment]
Hi @ashwinnaircy sorry I didn't have enough free time to take this further. Is your pull request taking care of everything? I could take a few minutes to test it, if you have your firmware in a repo somewhere.

**Comment by ashwinnaircy** [comment]
HI @zougloub  - sorry for the delayed reply. The firmware source is available at [EZ-USB™ FX3 Explorer kit as 16-channel 100 MHz logic analyzer with sigrok PulseView - KBA233652](https://community.cypress.com/t5/Knowledge-Base-Articles/EZ-USB-FX3-Explorer-kit-as-16-channel-100-MHz-logic-analyzer/ta-p/283993). Do check it out!

**Comment by zougloub** [comment]
@ashwinnaircy I'll check out your merge request but since I think it's interesting to keep this work also (due to the additional tooling/licensing constraints that come with your firmware) I'll take some time to refresh this branch.

**Comment by zougloub** [comment]
@zeldin I submitted https://github.com/sigrokproject/libsigrok/pull/154 with a rebased version of this branch (which I haven't tested yet). I invite you to follow up there and I'll close this PR, since your fork is a tad behind.

**Pull request closed without merging**
